Post http://localhost.myvtmi.im:8000/admin/location/team/1/4/1/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5NzZiZTlhLWFlOTYtNDFjZS04OGYxLWJjMDA1NDc4NjRlOCIsImVtYWlsIjoidGgubHVpekBnbWFpbC5jb20iLCJuYW1lIjoiVGhpYWdvIEx1aXogU2lsdmEiLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNTgyNjg0NzE2LCJleHAiOjE1ODMwNDQ3MTZ9.lzpzawBl1hi8dXvQNCMkg28HNNeTRcToAVwyfl-AKEM