GET http://localhost.myvtmi.im:8000/presence
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5NzZiZTlhLWFlOTYtNDFjZS04OGYxLWJjMDA1NDc4NjRlOCIsImVtYWlsIjoidGgubHVpekBnbWFpbC5jb20iLCJuYW1lIjoiVGhpYWdvIEx1aXogU2lsdmEiLCJpYXQiOjE1ODI2ODA3NTgsImV4cCI6MTU4MjcxNjc1OH0.v6DliE_C6VriAA-tVbzEVlCukJDhtj5tQ1TDbwH-RcM
